sudo: required
dist: trusty
before_install:
  - gem install bundler -v '< 2'
rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
  - 2.1.10
  - jruby
gemfile:
  - Gemfile
  - spec/gemfiles/i18n_0.7.gemfile
  - spec/gemfiles/i18n_0.8.gemfile
  - spec/gemfiles/i18n_0.9.gemfile
  - spec/gemfiles/i18n_1.0.gemfile
notifications:
  slack:
    secure: dPiP4+6xO6L9/RfXyivr2X2UohSD8CDdnnY57BvNgGVvFtQ2LUP9s1mDxj7gbBGhRZJzTMZlM/PU7bT9O9JCJPcpUs4dWg748KZ0ZGOslnv8yfzNbRh9U5OzyEjch2PFkEhpQPnuVCiof+ahjfxQQSkokpsbNa9DLlDmUapXFPY=
